name: Build+Test+Package

on:
  workflow_dispatch:
  pull_request:
    types:
      - opened
      - synchronize
  push:
    branches:
      - master

env:
  UNREAL_PATH: D:\unreal\UE_5.6
  PROJECT_NAME: CoopGameFleep.uproject
  TEST_SUITE_TO_RUN: CoopGameFleepTests.
  TEST_REPORT_FOLDER: TestResults
  TEST_LOGNAME: RunTests.log
  TARGET_NAME: CoopGameFleep
  PACKAGE_FOLDER: PackageResults
  PACKAGE_SHIPPING_FOLDER: PackageShippingResults
  UNREAL_EDITOR_CMD: UnrealEditor-Cmd.exe

jobs:
  build:
    name: Build+Test+Package
    runs-on: self-hosted

    steps:

    - name: Cleanup
      run: rm -Recurse ${{github.workspace}}\*

    - name: Clone repository
      uses: actions/checkout@v3

    - name: Build
      run: .\scripts\Build.bat $env:UNREAL_PATH (Get-Location).Path $env:PROJECT_NAME

    - name: Test
      run: .\scripts\RunTests.bat $env:UNREAL_PATH (Get-Location).Path $env:PROJECT_NAME $env:TEST_SUITE_TO_RUN $env:TEST_REPORT_FOLDER $env:TEST_LOGNAME $env:UNREAL_EDITOR_CMD

    - name: Archive test results
      uses: actions/upload-artifact@v3
      if: always()
      with:
        if-no-files-found: ignore
        name: test-results
        path: |
          ${{env.TEST_REPORT_FOLDER}}
          Saved\Logs\${{env.TEST_LOGNAME}}

    - name: Rebuild Lighting
      run: .\scripts\RebuildLighting.bat $env:UNREAL_PATH (Get-Location).Path $env:PROJECT_NAME $env:UNREAL_EDITOR_CMD Preview P_TestMap

    - name: Package
      run: .\scripts\Package.bat $env:UNREAL_PATH (Get-Location).Path $env:PROJECT_NAME $env:TARGET_NAME $env:PACKAGE_FOLDER

    - name: Compress package
      run: .\scripts\CompressPackage.bat (Get-Location).Path $env:PACKAGE_FOLDER

    - name: Archive package
      uses: actions/upload-artifact@v3
      if: always()
      with:
        if-no-files-found: ignore
        name: win64-build
        path: |
          ${{env.PACKAGE_FOLDER}}.zip
