name: Build and Test

on: [push, pull_request]

env:
  UNREAL_PATH: E:\unreal\UE_5.2
  PROJECT_NAME: CoopGameFleep.uproject
  TEST_SUITE_TO_RUN: CoopGameFleepTests.
  TEST_REPORT_FOLDER: TestResults
  TEST_LOGNAME: RunTests.log
  TARGET_NAME: CoopGameFleep
  PACKAGE_FOLDER: PackageResults

jobs:
  build:
    name: Build and Test
    runs-on: self-hosted

    steps:
    - name: Clone repository
      uses: actions/checkout@v3

    - name: Build
      run: .\scripts\Build.bat $env:UNREAL_PATH (Get-Location).Path $env:PROJECT_NAME

    - name: Test
      run: .\scripts\RunTests.bat $env:UNREAL_PATH (Get-Location).Path $env:PROJECT_NAME $env:TEST_SUITE_TO_RUN $env:TEST_REPORT_FOLDER $env:TEST_LOGNAME

    - name: Archive test results
      uses: actions/upload-artifact@v3
      if: always()
      with:
        if-no-files-found: ignore
        name: test-results
        path: |
          ${{env.TEST_REPORT_FOLDER}}
          Saved\Logs\${{env.TEST_LOGNAME}}

  package:
    name: Package
    needs: build
    runs-on: self-hosted

    steps:
    - name: Clone repository
      uses: actions/checkout@v3

    - name: Package
      run: .\scripts\Package.bat $env:UNREAL_PATH (Get-Location).Path $env:PROJECT_NAME $env:TARGET_NAME $env:PACKAGE_FOLDER

    - name: Archive package
      uses: actions/upload-artifact@v3
      if: always()
      with:
        if-no-files-found: ignore
        name: win64-build
        path: |
          ${{env.PACKAGE_FOLDER}}
