name: Example run self-hosted

on: [push, pull_request]

jobs:
  example:
    runs-on: self-hosted

    steps:
    - name: Clone repository
      uses: actions/checkout@v3

    - name: Try to run UAT
      shell: pwsh
      run: & 'E:\unreal\UE_5.2\Engine\Build\BatchFiles\RunUAT.bat' BuildCookRun -help
