name: Example run self-hosted

on: [push, pull_request]

env:
  UNREAL_PATH: E:\unreal\UE_5.2
  PROJECT_NAME: CoopGameFleep.uproject

jobs:
  example:
    runs-on: self-hosted

    steps:
    - name: Clone repository
      uses: actions/checkout@v3

    - name: Try to run UAT
      run: .\scripts\Build.bat $env:UNREAL_PATH $env:PROJECT_PATH $env:PROJECT_NAME
      env:
        PROJECT_PATH: (Get-Location).Path
