name: Example run self-hosted

on: [push, pull_request]

env:
  UNREAL_PATH: E:\unreal\UE_5.2

jobs:
  example:
    runs-on: self-hosted

    steps:
    - name: Clone repository
      uses: actions/checkout@v3

    - name: Try to run UAT
      run: .\scripts\Build.bat $env:UNREAL_PATH (Get-Location).Path
